config/routes.rb
Lalaalu::Application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"

  mailboxes_for :users

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }, 
             :controllers => { 
                :registrations => "users/registrations", 
                :passwords => "users/passwords",
                :sessions => "users/sessions"
              }
  match 'kid_products' => 'users/favourites#kid_products' 
  match 'nyc_restaurants' => 'users/favourites#nyc_restaurants' 
  match 'nyc_spots' => 'users/favourites#nyc_spots' 
  match 'nyc_playgrounds' => 'users/favourites#nyc_playgrounds'

  match 'save_avatar' => 'users/spouses#save_avatar'
  match 'pages/:slug' => 'pages#show', :as => :pages
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/admin' => 'admin/pages#index'
  get '/subscribe-kidboxes'=> 'kidboxes#subscribe', :as => 'subscribe_kidboxes'
  post '/subscribe-kidboxes'=> 'kidboxes#subscribe'
  get '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  post '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  match '/user-subscribe', :to =>'kidboxes#post_subscribe'

  match '/user_subscriptions/:id/continue_checkout', :to =>'user_subscriptions#continue_checkout'

  match '/user_subscriptions/:id/new', :to =>'user_subscriptions#new'

  match '/blogs/categories/:slug' => 'blogs#categories', :as => :blogs_category
  get '/calculate_price' => 'kidboxes#calculate_price'
  match '/users/invitations/generate_token' => 'users/invitations#generate_token'

  match '/users/dashboard' => 'users/dashboard#index'
  
  resources :home
  resources :line_items
  resources :news_letters
  resources :pages
  resources :blogs
  resources :kidboxes
  resources :order_receipts
  resources :user_subscriptions do
    get :final_verification  
  end

  resources :profiles
  resources :spouses
  resources :faqs
  resources :family_curators

  namespace :users do
    resources :spouses
    resources :children
    resources :favourites
    resources :invitations
    resources :friendships
    get 'compose_message/:id', :to => 'friendships#compose_message'
    post "messages/send_message" => "messages#send_message"
    get "messages/del_msg/:id" => "messages#del_msg"
    get "messages/back_inbox/:id" => "messages#back_inbox"
    get "messages/del_all_msgs" => "messages#del_all_msgs"
    resources :messages
    resources :boxes
  end

  namespace :admin do 
    resources :boxes
    resources :packages
    resources :categories
    resources :family_curators
    resources :brands
    resources :coupons
    resources :faqs
    resources :feeds
    resources :products
    resources :settings
    resources :orders
    match '/orders/:id/paymentstatus', :to => "orders#toggled_status"
    match '/blog_posts', :to => "pages#blogs", :as => 'blog_posts'
    resources :users
    resources :pages
    resources :subscriptions
    resources :agegroups
    resources :users
    resources :city_scopes
  end
  
  
  root :to => 'home#index'

end

app/views/admin/pages/_form.html.haml
= simple_form_for [ :admin, @page ], wrapper: :unicorn do |f|
  = f.error_notification

  = f.input :title
  
  = f.association :author, collection: @users, label_method: lambda { |user| user.profile.full_name if user.profile.present? }, value_method: :id, include_blank: true, :prompt => "Choose an Author"
  
  = f.association :category, collection: @categories,label_method: :name, value_method: :id, include_blank: true,:prompt => "Choose a Category"
  
  = f.input :unpublished, as: :radio_buttons, :checked =>  @page.unpublished?
  = f.input :show_title, as: :radio_buttons, :checked => @page.show_title?
  = f.input :slug

  = f.input :body, :as => :ckeditor, :label => false, :input_html => { :toolbar => 'Full' }
  .form-actions
    = styled_form_button( @page.new_record? ? 'create' : 'update')
    = styled_form_button 'reset'

app/views/admin/pages/edit.html.haml
- content_for :title, 'Edit Page'
.widget-content.nopadding
	= render 'form'

.form_nav
	= styled_button 'show', page_path(@page)
	= styled_button 'back', admin_pages_path

app/views/admin/pages/index.html.haml
.widget-content.nopadding
  %table.table.table-bordered
    %thead
      %tr
        %th Page Title
        %th Slug
        %th Link
        %th Published
        %th Category
        %th Actions
    %tbody
      -unless @pages.blank?
        -@pages.each do |page|
          %tr
            %td= page.title
            %td= page.slug
            %td= pages_path(page)
            %td.center_it= (page.unpublished) ? "No" : "Yes"
            %td= page.category.name if page.category
            %td.center_it
              = styled_button 'show', page_path(page)
              = styled_button 'edit', edit_admin_page_path(page)
              = styled_button 'delete', admin_page_path(page), method: :delete, confirm: 'Are You Sure!'
      -else
        %tr
          %td{:colspan=>4} No records found

- content_for :pagination, (paginate @pages, theme: :'twitter-bootstrap')
- content_for :new_record, (styled_button 'new', new_admin_page_path)

app/views/admin/pages/new.html.haml
- content_for :title, 'New Page'
.widget-content.nopadding
	= render 'form'

.form_nav
	= styled_button 'back', admin_pages_path