config/routes.rb
Lalaalu::Application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"

  mailboxes_for :users

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }, 
             :controllers => { 
                :registrations => "users/registrations", 
                :passwords => "users/passwords",
                :sessions => "users/sessions"
              }
  match 'kid_products' => 'users/favourites#kid_products' 
  match 'nyc_restaurants' => 'users/favourites#nyc_restaurants' 
  match 'nyc_spots' => 'users/favourites#nyc_spots' 
  match 'nyc_playgrounds' => 'users/favourites#nyc_playgrounds'

  match 'save_avatar' => 'users/spouses#save_avatar'
  match 'pages/:slug' => 'pages#show', :as => :pages
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/admin' => 'admin/pages#index'
  get '/subscribe-kidboxes'=> 'kidboxes#subscribe', :as => 'subscribe_kidboxes'
  post '/subscribe-kidboxes'=> 'kidboxes#subscribe'
  get '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  post '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  match '/user-subscribe', :to =>'kidboxes#post_subscribe'

  match '/user_subscriptions/:id/continue_checkout', :to =>'user_subscriptions#continue_checkout'

  match '/user_subscriptions/:id/new', :to =>'user_subscriptions#new'

  match '/blogs/categories/:slug' => 'blogs#categories', :as => :blogs_category
  get '/calculate_price' => 'kidboxes#calculate_price'
  match '/users/invitations/generate_token' => 'users/invitations#generate_token'

  match '/users/dashboard' => 'users/dashboard#index'
  
  resources :home
  resources :line_items
  resources :news_letters
  resources :pages
  resources :blogs
  resources :kidboxes
  resources :order_receipts
  resources :user_subscriptions do
    get :final_verification  
  end

  resources :profiles
  resources :spouses
  resources :faqs
  resources :family_curators

  namespace :users do
    resources :spouses
    resources :children
    resources :favourites
    resources :invitations
    resources :friendships
    get 'compose_message/:id', :to => 'friendships#compose_message'
    post "messages/send_message" => "messages#send_message"
    get "messages/del_msg/:id" => "messages#del_msg"
    get "messages/back_inbox/:id" => "messages#back_inbox"
    get "messages/del_all_msgs" => "messages#del_all_msgs"
    resources :messages
    resources :boxes
  end

  namespace :admin do 
    resources :boxes
    resources :packages
    resources :categories
    resources :family_curators
    resources :brands
    resources :coupons
    resources :faqs
    resources :feeds
    resources :products
    resources :settings
    resources :orders
    match '/orders/:id/paymentstatus', :to => "orders#toggled_status"
    match '/blog_posts', :to => "pages#blogs", :as => 'blog_posts'
    resources :users
    resources :pages
    resources :subscriptions
    resources :agegroups
    resources :users
    resources :city_scopes
  end
  
  
  root :to => 'home#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  has_many :products
  # attr_accessible :created_by, :description, :name, :brand_image, :remote_brand_image_url
  mount_uploader :brand_image, BrandImageUploader
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < Admin::AdminsController
	def index
		@brands = Brand.order('name ASC').page params[:page]
    authorize! :read, @brands
	end
	
	def show
    @brand = Brand.find(params[:id])
    authorize! :read, @brand
  end

  def new
    @brand = Brand.new
    authorize! :create, @brand
  end
  
  def create
    @brand = Brand.new(permitted_params.for_brand)
    authorize! :create, @brand
    if @brand.save
      redirect_to admin_brands_path, notice: "Brand has been created."
    else
      render 'new'
    end
  end

  def edit
    @brand = Brand.find(params[:id])
    authorize! :update, @brand
  end
  
  def update
    @brand = Brand.find(params[:id])
    authorize! :update, @brand
    if @brand.update_attributes(permitted_params.for_brand)
      redirect_to admin_brand_path, notice: 'Brand was successfully updated.'
    else
      render action: "edit"
    end
  end
  
  def destroy
    @brand = Brand.find(params[:id])
    authorize! :destroy, @brand
    @brand.destroy
    redirect_to admin_brands_url
  end

end

app/views/admin/brands/_form.html.haml
= simple_form_for [ :admin, @brand ], wrapper: :unicorn do |f|
  = f.error_notification

  = f.input :name, as: :string
  = f.input :description, as: :text
  = f.input :brand_image, as: :file      
  .form-actions
    = @brand.new_record? ? (styled_form_button 'create') : (styled_form_button 'update')
    = styled_form_button 'reset'

app/views/admin/brands/edit.html.haml
- content_for :title, 'Edit Brand'
.widget-content.nopadding
	= render 'form'

.form_nav
	= styled_button 'show', admin_brand_path(@brand)
	= styled_button 'back', admin_brands_path

app/views/admin/brands/index.html.haml
.widget-content.nopadding
  %table.table.table-bordered
    %tr
      %th Name
      %th Description
      %th Actions
    - unless @brands.blank?
      - @brands.each do |brand|
        %tr
          %td= h brand.name
          %td= h brand.description
          %td.center_it
            = styled_button 'show', admin_brand_path(brand)
            = styled_button 'edit', edit_admin_brand_path(brand)
            = styled_button 'delete', admin_brand_path(brand), method: :delete, confirm: 'Are You Sure!'
    - else
      %tr
        %td{:colspan=>3} No records found

- content_for :pagination, (paginate @brands, theme: :'twitter-bootstrap')
- content_for :new_record, (styled_button 'new', new_admin_brand_path)

app/views/admin/brands/new.html.haml
- content_for :title, 'New Brand'
.widget-content.nopadding
	= render 'form'

.form_nav	
	= styled_button 'back', admin_brands_path

app/views/admin/brands/show.html.haml
.widget-content.nopadding
	%table.table.table-bordered
		%thead
			%tr
				%td Name
				%td= @brand.name
			%tr
				%td Description
				%td= strip_tags @brand.description
			%tr
				%td Image
				%td= image_tag @brand.brand_image_url(:thumb) if @brand.brand_image?
			%tr
				%td Products
				%td
					%ol
						- @brand.products.each do |product|
							%li= link_to product.name, admin_product_path(product)
			%tr
				%td
				%td
					= styled_button 'back', admin_brands_path
					= styled_button 'edit', edit_admin_brand_path(@brand)
					= styled_button 'delete', admin_brand_path(@brand), method: :delete, confirm: 'Are You Sure!'