config/routes.rb
Lalaalu::Application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"

  mailboxes_for :users

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }, 
             :controllers => { 
                :registrations => "users/registrations", 
                :passwords => "users/passwords",
                :sessions => "users/sessions"
              }
  match 'kid_products' => 'users/favourites#kid_products' 
  match 'nyc_restaurants' => 'users/favourites#nyc_restaurants' 
  match 'nyc_spots' => 'users/favourites#nyc_spots' 
  match 'nyc_playgrounds' => 'users/favourites#nyc_playgrounds'

  match 'save_avatar' => 'users/spouses#save_avatar'
  match 'pages/:slug' => 'pages#show', :as => :pages
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/admin' => 'admin/pages#index'
  get '/subscribe-kidboxes'=> 'kidboxes#subscribe', :as => 'subscribe_kidboxes'
  post '/subscribe-kidboxes'=> 'kidboxes#subscribe'
  get '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  post '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  match '/user-subscribe', :to =>'kidboxes#post_subscribe'

  match '/user_subscriptions/:id/continue_checkout', :to =>'user_subscriptions#continue_checkout'

  match '/user_subscriptions/:id/new', :to =>'user_subscriptions#new'

  match '/blogs/categories/:slug' => 'blogs#categories', :as => :blogs_category
  get '/calculate_price' => 'kidboxes#calculate_price'
  match '/users/invitations/generate_token' => 'users/invitations#generate_token'

  match '/users/dashboard' => 'users/dashboard#index'
  
  resources :home
  resources :line_items
  resources :news_letters
  resources :pages
  resources :blogs
  resources :kidboxes
  resources :order_receipts
  resources :user_subscriptions do
    get :final_verification  
  end

  resources :profiles
  resources :spouses
  resources :faqs
  resources :family_curators

  namespace :users do
    resources :spouses
    resources :children
    resources :favourites
    resources :invitations
    resources :friendships
    get 'compose_message/:id', :to => 'friendships#compose_message'
    post "messages/send_message" => "messages#send_message"
    get "messages/del_msg/:id" => "messages#del_msg"
    get "messages/back_inbox/:id" => "messages#back_inbox"
    get "messages/del_all_msgs" => "messages#del_all_msgs"
    resources :messages
    resources :boxes
  end

  namespace :admin do 
    resources :boxes
    resources :packages
    resources :categories
    resources :family_curators
    resources :brands
    resources :coupons
    resources :faqs
    resources :feeds
    resources :products
    resources :settings
    resources :orders
    match '/orders/:id/paymentstatus', :to => "orders#toggled_status"
    match '/blog_posts', :to => "pages#blogs", :as => 'blog_posts'
    resources :users
    resources :pages
    resources :subscriptions
    resources :agegroups
    resources :users
    resources :city_scopes
  end
  
  
  root :to => 'home#index'

end

app/views/layouts/admin/_commonFormElements.html.haml
.btn-group
	%a.btn.btn-large.tip-bottom{href: admin_pages_path,:title => "Manage Pages"}
		%i.icon-file
	%a.btn.btn-large.tip-bottom{href: admin_users_path ,:title => "Manage Users"}
		%i.icon-user
	%a.btn.btn-large.tip-bottom{:title => "Manage Comments"}
		%i.icon-comment
		%span.label.label-important 5
	%a.btn.btn-large.tip-bottom{href: admin_orders_path ,:title => "Manage Orders"}
		%i.icon-shopping-cart

app/views/layouts/admin/_currentnav.html.haml
#breadcrumb
	%a.tip-bottom{:href => "/admin/#{controller.controller_name}", :title => "Go to Home"}
		%i.icon-home
		= controller.controller_name.capitalize
	- unless controller.action_name == 'index'
		%a.current{:href => "#"} 
			= controller.action_name.capitalize

app/views/layouts/admin/_flash_messages.html.haml
- [:alert, :notice, :error].each do |type|
	- if flash[type].present?
		-css_class = "alert-info" if type == :alert
		-css_class = "alert alert-error" if type == :error
		-css_class = "alert alert-success" if type == :notice
		%div{:class => "alert #{css_class}", :style => "margin: 0;" }
			%button.close{"data-dismiss" => "alert"} ×
			= flash[type]

app/views/layouts/admin/_sidenav.html.haml
#sidebar
  / %a.visible-phone{:href => "#"}
  /   %i.icon.icon-home
  /   Dashboard
  %ul
    =# link_li 'icon','name',url (optional)
    = link_li 'icon-eject', 'front end', root_url
    =# link_li 'icon-home', 'home', admin_pages_path
    %li.submenu
      %a{:href => "#"}
        %i{:class => "icon icon-th-list"}
        %span CMS
        %span{:class => :label} 6
      %ul{:style => "display:none"}
        = link_li 'icon-file', 'pages'
        = link_li 'icon-th-list', 'categories'
        = link_li 'icon-envelope', 'feeds'
        = link_li 'icon-question-sign', 'faqs'
        = link_li 'icon-question-sign', 'family_curators'
        = link_li 'icon-question-sign', 'blog_posts'
        = link_li 'icon-question-sign', 'city_scopes'
        
    = link_li 'icon-user', 'users'
    = link_li 'icon-user', 'agegroups'
    = link_li 'icon-gift', 'boxes'
    = link_li 'icon-tag', 'brands'
    = link_li 'icon-tags', 'products'
    = link_li 'icon-shopping-cart', 'orders'
    = link_li 'icon-thumbs-down', 'coupons'
    = link_li 'icon-shopping-cart', 'subscriptions'
    = link_li 'icon-wrench', 'settings'

app/views/layouts/admin/_usernav.html.haml
#user-nav.navbar.navbar-inverse
  %ul.nav.btn-group
    %li.btn.btn-inverse
      = link_to content_tag(:i, nil, class: 'icon icon-user').concat('Profile'), admin_user_path(0,profile: 'my')
    %li#menu-messages.btn.btn-inverse.dropdown
      %a.dropdown-toggle{"data-target" => "#menu-messages", "data-toggle" => "dropdown", :href => "#"}
        %i.icon.icon-envelope
        %span.text Messages
        %span.label.label-important 5
        %b.caret
      %ul.dropdown-menu
        %li
          %a.sAdd{:href => "#", :title => ""} new message
        %li
          %a.sInbox{:href => "#", :title => ""} inbox
        %li
          %a.sOutbox{:href => "#", :title => ""} outbox
        %li
          %a.sTrash{:href => "#", :title => ""} trash
    %li.btn.btn-inverse
      = link_to content_tag(:i, nil, class: 'icon icon-cog').concat('Settings'), admin_settings_path
    %li.btn.btn-inverse
      = link_to content_tag(:i,nil, class: 'icon icon-share-alt').concat(content_tag(:span, 'Logout',class: 'text')), destroy_user_session_path, method: :delete