config/routes.rb
Lalaalu::Application.routes.draw do

  mount Ckeditor::Engine => "/ckeditor"

  mailboxes_for :users

  devise_for :users, path_names: { sign_in: "login", sign_out: "logout" }, 
             :controllers => { 
                :registrations => "users/registrations", 
                :passwords => "users/passwords",
                :sessions => "users/sessions"
              }
  match 'kid_products' => 'users/favourites#kid_products' 
  match 'nyc_restaurants' => 'users/favourites#nyc_restaurants' 
  match 'nyc_spots' => 'users/favourites#nyc_spots' 
  match 'nyc_playgrounds' => 'users/favourites#nyc_playgrounds'

  match 'save_avatar' => 'users/spouses#save_avatar'
  match 'pages/:slug' => 'pages#show', :as => :pages
  post '/tinymce_assets' => 'tinymce_assets#create'
  get '/admin' => 'admin/pages#index'
  get '/subscribe-kidboxes'=> 'kidboxes#subscribe', :as => 'subscribe_kidboxes'
  post '/subscribe-kidboxes'=> 'kidboxes#subscribe'
  get '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  post '/gift-kidboxes'=> 'kidboxes#subscribe_gift'
  match '/user-subscribe', :to =>'kidboxes#post_subscribe'

  match '/user_subscriptions/:id/continue_checkout', :to =>'user_subscriptions#continue_checkout'

  match '/user_subscriptions/:id/new', :to =>'user_subscriptions#new'

  match '/blogs/categories/:slug' => 'blogs#categories', :as => :blogs_category
  get '/calculate_price' => 'kidboxes#calculate_price'
  match '/users/invitations/generate_token' => 'users/invitations#generate_token'

  match '/users/dashboard' => 'users/dashboard#index'
  
  resources :home
  resources :line_items
  resources :news_letters
  resources :pages
  resources :blogs
  resources :kidboxes
  resources :order_receipts
  resources :user_subscriptions do
    get :final_verification  
  end

  resources :profiles
  resources :spouses
  resources :faqs
  resources :family_curators

  namespace :users do
    resources :spouses
    resources :children
    resources :favourites
    resources :invitations
    resources :friendships
    get 'compose_message/:id', :to => 'friendships#compose_message'
    post "messages/send_message" => "messages#send_message"
    get "messages/del_msg/:id" => "messages#del_msg"
    get "messages/back_inbox/:id" => "messages#back_inbox"
    get "messages/del_all_msgs" => "messages#del_all_msgs"
    resources :messages
    resources :boxes
  end

  namespace :admin do 
    resources :boxes
    resources :packages
    resources :categories
    resources :family_curators
    resources :brands
    resources :coupons
    resources :faqs
    resources :feeds
    resources :products
    resources :settings
    resources :orders
    match '/orders/:id/paymentstatus', :to => "orders#toggled_status"
    match '/blog_posts', :to => "pages#blogs", :as => 'blog_posts'
    resources :users
    resources :pages
    resources :subscriptions
    resources :agegroups
    resources :users
    resources :city_scopes
  end
  
  
  root :to => 'home#index'

end

app/models/city_scope.rb
class CityScope < ActiveRecord::Base
  attr_accessible :image_url, :redirect_url ,:upload
  mount_uploader :upload, CityScopeUploader
    
end

app/controllers/admin/city_scopes_controller.rb
class Admin::CityScopesController < ApplicationController
    
  def index
    @city_scopes = CityScope.find(:all)
    #@city_scopes = CityScope.find(:all)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @city_scopes }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @city_scope = CityScope.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city_scope }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @city_scope = CityScope.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city_scope }
    end
  end

  def edit
    @city_scope = CityScope.find(params[:id])
  end

  def create
    @city_scope = CityScope.new(:upload=>params[:city_scope][:upload],:redirect_url=>params[:city_scope][:redirect_url])

    if @city_scope.save
      redirect_to admin_city_scopes_path, notice: "City Scope has been created."
    else
      render 'new'
    end
  end

  def update
    @city_scope = CityScope.find(params[:id])

    respond_to do |format|
      if @city_scope.update_attributes(params[:upload])
        format.html { redirect_to @city_scope, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city_scope.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy
    @city_scope = CityScope.find(params[:id])
    authorize! :destroy, @city_scope
    @city_scope.destroy
    respond_to do |format|
      format.html { redirect_to admin_city_scopes_url }
      format.json { head :no_content }
    end
  end
  
end

app/views/admin/city_scopes/_form.html.haml
= simple_form_for [ :admin , @city_scope ], wrapper: :unicorn do |f|
  = f.error_notification

  = f.input :redirect_url, as: :string
  = f.input :upload, as: :file
  
  .form-actions
    = @city_scope.new_record? ? (styled_form_button 'create') : (styled_form_button 'update')
    = styled_form_button 'reset'

app/views/admin/city_scopes/index.html.haml
.widget-content.nopadding
  %table.table.table-bordered
    %tr
      %th Redirect Url
      %th Image Url
    - unless @city_scopes.blank?
      - @city_scopes.each do |scope|
        %tr
          %td= h scope.redirect_url
          %td= h scope.image_url
          %td.center_it
            = styled_button 'show', admin_city_scopes_path(scope)
            = styled_button 'edit', edit_admin_city_scope_path(scope)
            = styled_button 'delete', admin_city_scope_path(scope), method: :delete, confirm: 'Are You Sure!'
    - else
      %tr
        %td{:colspan=>3} No records found

- content_for :new_record, (styled_button 'new', new_admin_city_scope_path)

app/views/admin/city_scopes/new.html.haml
- content_for :title, 'New City Scope'
.widget-content.nopadding
	= render 'form'

.form_nav	
	= styled_button 'back', admin_city_scopes_path